#!/usr/bin/env ruby

require 'pry'

def f(a,len)
  n,z,y,x = 0,0,0,0
  while n != len do
    if a[n] < 0
      z,y = z+y,y+1
    elsif a[n] == 0
      z,y,x = z + n,y+1,x+1
    elsif a[n] > 0
      z,x = z+x,x+1
    end
    n = n+1
  end
  z
end

binding.pry